# Generated by Django 5.2.1 on 2025-07-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantsapp', '0007_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='added_at',
        ),
    ]
